<?php

use PHPUnit\Framework\TestCase;

class TestAccounting extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->accounting = new Accounting();
    }

    public function testQueryOneMonth()
    {
    }
}
